# =================================== Base settings ====================================
baseURL = 'https://domain.com/'
languageCode = 'en-us'
title = 'My Blog'
theme = "Hugo-Awesome-Remastered"
svg = "pfp.png"
# ======================================================================================



# =================================== Author settings ==================================
[params.author]
  avatar = "pfp.png" # put the file in assets folder; also ensure that image has same height and width
  intro = "Blog"
  name = "0x0060"
  description = "Blog Description"
  
  # Blog Post
  writterName = "ren"
  writterLink = "https://0x0060.dev/"

# ======================================================================================


# =================================== Homepage settings ==================================
[params.websiteHome]
  footerText = "Here text or domain.com copyright thing"
# ======================================================================================


# =================================== Browser configuration ============================
[params.browserconfig]
TileColor = "#2d89ef" # default windows 10 blue tile color
# =======================================================================================


# =================================== Social Icons (currently commented out) ===========
#[[params.socialIcons]]
#name = "github"
#url = "https://github.com/ByteShifters"

#[[params.socialIcons]]
#name = "twitter"
#url = "https://twitter.com/ByteShifters"

#[[params.socialIcons]]
#name = "instagram"
#url = "https://instagram.com/ByteShifters"

#[[params.socialIcons]]
#name = "email"
#url = "mailto:us@byteshifters.com"
#languageCode = 'en-us'

#[[params.socialIcons]]
#name = "Rss"
#url = "index.xml"
#languageCode = 'en-us'
# ======================================================================================


# =================================== Default content language =========================
defaultContentLanguage = "en-gb"
# ======================================================================================


# =================================== Enable emojis globally ===========================
enableEmoji = true
# ======================================================================================


# =================================== Ignore specific errors ===========================
ignoreErrors = ["additional-script-loading-error"] # ignore error of loading additional scripts.
# ======================================================================================


# =================================== Markup settings ==================================
[markup]
  [markup.highlight]
    noClasses = false
    style = 'github-dark'
    tabWidth = 4

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.tableOfContents]
    startLevel = 2 # ToC starts from H2
    endLevel = 4   # ToC ends at H4
    ordered = false # generates <ul> instead of <ol>
# ======================================================================================


# =================================== Menu settings ====================================
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4
# ======================================================================================


# =================================== Taxonomies =======================================
[taxonomies]
  tag = 'tags'
# ======================================================================================


# =================================== Additional settings ===============================
[params]
  favicon = "transp.png"
  goToTop = true
# ======================================================================================


# =================================== Pagination settings ==============================
paginate = 5
# ======================================================================================


# =================================== Build settings ===================================
_build.list = "never"
# ======================================================================================
